# Generated by Django 4.2.4 on 2023-08-14 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 9, 40, 34, 959429, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 8, 14, 9, 40, 41, 958904, tzinfo=datetime.timezone.utc), upload_to='media/post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 9, 40, 49, 441781, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 8, 14, 9, 40, 54, 828265, tzinfo=datetime.timezone.utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
